name: Build and Deploy
on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: src
      - name: Checkout current
        uses: actions/checkout@v2
        with:
          ref: main
          path: live
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install npm and deps
        run: |
          npm install -g npm@7
          cd src
          npm install
      - name: Build site
        run: |
          cd src
          npm run build
      - name: Prepare deployment
        run: |
          rm -rf live/*
          cp -r src/public/* live
      - name: Commit & deploy
        uses: EndBug/add-and-commit@v4
        with:
          cwd: "live"
          ref: "main"
          message: "deploy: ${{ github.sha }}"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.com"
